---

# WAN Fabric Settings

fabric_name: WAN
use_anta: true
deploy_to_cv_accept_preview: true
deploy_to_cv_inventory_host: cloudvision

custom_structured_configuration_prefix:
  - custom_structured_configuration_
  - group_custom_structured_
  - host_custom_structured_

# Ansible connectivity definitions
# eAPI connectivity via HTTPS is specified (as opposed to CLI via SSH)
ansible_connection: ansible.netcommon.httpapi
# Specifies that we are indeed using Arista EOS
ansible_network_os: arista.eos.eos
# This user/password must exist on the switches to enable Ansible access
ansible_user: ansible
ansible_password: ansible
# User escalation (to enter enable mode)
ansible_become: true
ansible_become_method: enable
# Use SSL (HTTPS)
ansible_httpapi_use_ssl: true
# Do not try to validate certs
ansible_httpapi_validate_certs: false

mgmt_interface_vrf: default
mgmt_gateway: null
name_servers:
  - 169.254.169.254
dns_domain: sjc.aristanetworks.com

custom_structured_configuration_router_multicast:
  ipv4:
    software_forwarding: "kernel"

custom_structured_configuration_agents:
  - name: KernelFib
    environment_variables:
      - name: KERNELFIB_PROGRAM_ALL_ECMP
        value: "'true'"

custom_structured_configuration_aliases: |
  alias cc clear counters
  alias cpc clear platform trident counters
  alias senz show interface counter error | nz
  alias shmc show int | awk '/^[A-Z]/ { intf = $1 } /, address is/ { print intf, $6 }'
  alias snz show interface counter | nz
  alias sqnz show interface counter queue | nz
  alias srnz show interface counter rate | nz
  username admin role network-admin privilege 15 secret sha512 $6$ZV5Le12banee6hLp$D/IpUVs3cgyS4Q.xi8xKfBMqmtlOmmG6IXKn6KbOS4cQvVToTz9ZbJRqhqLLTZxS4NLpJZUJPGu7FxJB0v/OY0
  username cvpadmin secret sha512 $6$n8E8Ext.IOGWnQ7x$YLtZIEHAzz.hmOUKbmcehhDWAc2/oVcTUNQkHgqCnSSYCqRJy5Q3OgLynORM3iiiNzMZ0HvpbzcXiRYxOL9yS/
  username cwomble secret *
  username cwomble ssh-key ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOZFQIhHNghkuJryYiNyFUbkVPyGH2tU1gFuoJ/wDDg420VY9tb1OQn7k+XoDaVWWoEoOek07sJzns0Yy7WYUhgHP3T8Q3qW2DRjRDCUgUXnt9iW9N/axh4U4OP71UbWJNw3D6b5JE4EWt56okFcR6eSAyyKoYZvUAiCX1oUGVbRDz0cTNTbbnYHXp8DFBM/3fLNrO7Ntif+1ZtY8IQoZoDaOZpQLqTt40QGBAJgyXy0xP3urSaSJP2alSZP0g2IY9WebHaJAKnzP+SCuU4pMpcWYE3EoevYB6RLy12WylXq7Ht8sy2cjB9HH19BM4lNvRJ7ArjsL8enBP4OdqdyCH/SfLy6YrQ2EFidNpxnGBNVxIA7lkK82jLGFiqKJJNapZW4nRljT+KVMFEh/NTDP61wYmUPCR331+e3TiKsapwcIN/Q1+20WBVf11RseChjLqZzu54y9PDw/MA8ra8mPbuenhNJ6Xw8nkZbeUr+o/jZHwTP0sTLFyv4uJKvOACBc=
  username ec2-user shell /bin/bash nopassword
  username ec2-user ssh-key ssh-rsa ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFhhvHS7TWbOyC7xeJOMglKEa4JgZBZiiu550xsFJFZpZKMx0BJM1Z9jGrEV0pEhltg5oiiGDcrviRvYpY2u2fHEL//QmC3dTn8QtCMq7zM2DLgqlPqhsl1n3+rmYYM4rBNyq+1HVT1QIMhWMw8k3Be0+hIbV/8SgH0kcuKzm5ZTU1atOexCB/HRUVP7nQq+NOwB8a4RuYIUIeGvK4kLrMDbt5MHAgWgtapkG/40HwhxWMqmkCMN3ZN1llHRYgade+MMisW1DCtnGLzHhrPJnP60wqEcyV4Bqa6KBR6LgIYk/Q7+WNkW2YClPF7q4GvdCUR8JEavIg624OlPp2moEFt4imrhHyqYaYFn3rP3iKvN0Jw/m9wUe+oAJybLic1F77IyDskpta+qAJOjlYcyDT+ebF6AeMTNBmpA1RzqOh2lL2aB1UxRWo+Cmt2pFrr28djzt3wGUFuds/N+RSW/9iN7PB53TI3sNNABrFzrHT1DvyskDrFsY8K+YURR6DY78= nonroot@buildkitsandbox
  username gcp-user secret *
  username gcp-user ssh-key ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGPEoZ2l67eEEwrlGfBAHPMx44IoqhyfjqXj2Ka4PxLuHgi1mv131VuCRlyWjOjddccyFUilfR1Bprdmd1Tj7o4Q11YQ138LOqFWJT3h0pxgHFdIHo70y4rI8aL15ixukZYa+g9KX8qTN+ZpFfea2d3CEFzMp+Y3xVPiWwLKzalq1JwT5J4MK2VHCbcnpN3zRON+gca/iZH9upA0WaXWJXNBnYXrgXFVGCJFk6Yl1ZXIGnEcKGe44c77zWgF4C66VhltsW999XD5vF31f6TTs25qxGScsiKMDg2uM1AzVg5KfxxhVy5HKd23YJJMytvUXL9h5Wq1HEEluSCcFtNI81
  username mircea secret *
  username mircea ssh-key ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDw26o1dbfin+wgiYhiHybYebcYlS1EpucVdzfZASTkaMnCiaGy61mLtCaiZA82MEMNbkHLr9WgO2f9pHN2fiIiJc2gmlZPAUvSDzOHQapGuWzoPbeoKTaPyEzkDD5IzerV8wgMooaJOIWU9dWRjVPpUyj2GJ3JirC3HiLRnhkHFh3F+vUkEL81lMzJ/0HdnW3WrIjU6JnuOnpjiJ+np1OEPSbBdANT89tzaEm87QUioPQF7hHknKFUYK2Zqh5SXR6vQaLEcIhRqlAvZyjc95vDtYFWzqrdrHTdznyr8Hs/R2OeLmPGArGm6V8sGC9Q1bGfbhwjxvoWH9igUO6d82HKL2h8PJ1gXJU4XCb6Dkft7y0M4CDx6tIOo9jDxwFRtim9oC0uwxsRoXL4xCDYGH+jO4RAQSVxP6MQsJBEOvXez6whUev1lR91CiXmtUwQfzfmol03U8xMsBkdZ+Y4B7AkBUIpi/+8aEbMwRACyDZJB0+FzkYuWIYpiqoQ4pwUVw8=
  username service shell /bin/bash secret sha512 $6$n8UTkktQgRXoe/cT$3k5JezugpzweKPQN5SPvnUyATeJEtsCZHIVeO.YhiWcFgUN10RRh9LstwdwVud9vrjArKECYZwISU1DA3dLBd.


cvp_instance_ips: ["10.18.148.247"]
custom_structured_configuration_daemon_terminattr:
  cvauth:
    token_file: "/tmp/cv-onboarding-token"
  disable_aaa: true

aaa_authorization:
  exec:
    default: local

custom_structured_configuration_system:
  l1:
    unsupported_speed_action: "error"
    unsupported_error_correction_action: "error"

custom_structured_configuration_spanning_tree:
  mode: mstp

clock:
  timezone: "PST8PDT"

ntp_settings:
  server_vrf: default
  servers:
    - name: 0.us.pool.ntp.org

custom_structured_configuration_snmp_server:
  communities:
    - name: public
      access: ro
